version: '3.8'

networks:
    php-postgres-node:

services:

    server:
        image: 'nginx:stable-alpine'
        ports:
        - '8000:80'
        volumes:
        - ./symfony:/var/www/html
        - ./Docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
        - php
        - db
        - node

    php:
        build:
            context: ./Docker
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./symfony:/var/www/html:delegated
        ports:
        - '3000:9000'
        networks:
            - php-postgres-node

    db:
        image: postgres
        container_name: postgres
        restart: always
        env_file:
        - ./Docker/postgres.env

    node:
        image: node:21-alpine3.17
        container_name: node
        ports:
            - "8001:8001"
        volumes:
          - ./nuxt:/home/node/app
        working_dir: /home/node/app
        networks:
            - php-postgres-node
        tty: true

    composer:
        build:
            context: ./Docker
            dockerfile: composer.dockerfile
        volumes:
        - ./symfony:/var/www/html

    symfony-console:
        build:
            context: ./Docker
            dockerfile: php.dockerfile
        volumes:
            - ./symfony:/var/www/html
        entrypoint: ["php", "/var/www/html/bin/console"]
